cc_library(
    name = "container",
    hdrs = [
        "include/container/chunked_hash_map.h",
        "include/container/contiguous_range_map.h",
        "include/container/fragmented_vector.h",
        "include/container/interval_set.h",
        "include/container/intrusive_list_helpers.h",
        "include/container/json.h",
        "include/container/lw_shared_container.h",
        "include/container/zip.h",
    ],
    includes = [
        "include",
    ],
    visibility = ["//visibility:public"],
)
