cc_library(
    name = "metrics",
    srcs = [
    ],
    hdrs = [
        "metrics.h",
        "metrics_registry.h",
    ],
    include_prefix = "metrics",
    deps = [
        "//src/v/ssx:ssx",
        "//src/v/utils:utils",
    ],
    visibility = ["//visibility:public"],
)
