cc_library(
    name = "metrics",
    srcs = [
    ],
    hdrs = [
        "metrics.h",
        "metrics_registry.h",
        "prometheus_sanitize.h",
    ],
    include_prefix = "metrics",
    visibility = ["//visibility:public"],
    deps = [
        "//src/v/ssx",
        "//src/v/utils",
    ],
)
