cc_library(
    name = "schema_registry_config",
    hdrs = [
        "schema_registry/schema_id_validation.h",
        "schema_registry/subject_name_strategy.h",
    ],
    include_prefix = "pandaproxy",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "schema_registry_interface",
    hdrs = [
        "schema_registry/fwd.h",
        "schema_registry/api.h",
        "schema_registry/validation.h",
    ],
    include_prefix = "pandaproxy",
    visibility = ["//visibility:public"],
)
