cc_library(
    name = "model",
    srcs = [
    ],
    hdrs = [
        "compression.h",
        "fundamental.h",
        "metadata.h",
        "timestamp.h",
    ],
    copts = [
    ],
    include_prefix = "model",
    visibility = ["//visibility:public"],
    deps = [
        "//src/v/bytes:bytes",
        "//src/v/serde:serde",
        "//src/v/utils:utils",
    ],
)
