cc_library(
    name = "model",
    srcs = [
    ],
    hdrs = [
        "compression.h",
        "fundamental.h",
        "metadata.h",
        "namespace.h",
        "timestamp.h",
        "validation.h",
        "timeout_clock.h",
        "record.h",
        "record_batch_types.h",
        "record_utils.h",
        "record_batch_reader.h",
        "limits.h",
        "adl_serde.h",
        "offset_interval.h",
        "async_adl_serde.h",
    ],
    copts = [
    ],
    include_prefix = "model",
    visibility = ["//visibility:public"],
    deps = [
        "//src/v/bytes",
        "//src/v/serde",
        "//src/v/utils",
        "//src/v/reflection",
    ],
)
