cc_library(
    name = "version",
    srcs = [
    ],
    hdrs = [
        "outcome_future_utils.h",
        "version.h",
        "vformat.h",
    ],
    include_prefix = "version",
    visibility = ["//visibility:public"],
    deps = [
    ],
)
