cc_library(
    name = "reflection",
    srcs = [
    ],
    hdrs = [
        "adl.h",
        "arity.h",
        "async_adl.h",
        "for_each_field.h",
        "to_tuple.h",
        "type_traits.h",
        "seastar/circular_buffer.h",
    ],
    copts = [
    ],
    include_prefix = "reflection",
    visibility = ["//visibility:public"],
    deps = [
    ],
)
