cc_library(
    name = "client",
    srcs = [
    ],
    hdrs = [
        "configuration.h",
        "fwd.h",
        "types.h",
    ],
    include_prefix = "kafka/client",
    visibility = ["//visibility:public"],
    deps = [
    ],
)
