cc_library(
    name = "resource_mgmt",
    srcs = [
    ],
    hdrs = [
        "io_priority.h",
    ],
    copts = [
    ],
    include_prefix = "resource_mgmt",
    visibility = ["//visibility:public"],
    deps = [
    ],
)
