cc_library(
    name = "resource_mgmt",
    srcs = [
    ],
    hdrs = [
        "io_priority.h",
        "available_memory.h",
        "memory_groups.h",
        "storage.h",
        "rate.h",
    ],
    copts = [
    ],
    include_prefix = "resource_mgmt",
    visibility = ["//visibility:public"],
    deps = [
    ],
)
