cc_library(
    name = "run_quota",
    hdrs = [
        "run_quota.h",
    ],
    include_prefix = "archival",
    visibility = ["//visibility:public"],
    deps = [
        "//src/v/utils",
    ],
)

