cc_library(
    name = "utils",
    srcs = [
    ],
    hdrs = [
        "functional.h",
        "hdr_hist.h",
        "mutex.h",
        "named_type.h",
        "static_deleter_fn.h",
        "vint.h",
        "type_traits.h",
        "tristate.h",
        "uuid.h",
        "unresolved_address.h",
        "xid.h",
        "to_string.h",
    ],
    copts = [
    ],
    include_prefix = "utils",
    visibility = ["//visibility:public"],
    deps = [
        "@hdrhistogram//:libhdrhistogram",
    ],
)
