cc_library(
    name = "utils",
    srcs = [
    ],
    hdrs = [
        "base64.h",
        "file_io.h",
        "functional.h",
        "hdr_hist.h",
        "inet_address_wrapper.h",
        "log_hist.h",
        "mutex.h",
        "named_type.h",
        "prefix_logger.h",
        "static_deleter_fn.h",
        "to_string.h",
        "tristate.h",
        "unresolved_address.h",
        "uuid.h",
        "vint.h",
        "xid.h",
        "stop_signal.h",
    ],
    copts = [
    ],
    include_prefix = "utils",
    visibility = ["//visibility:public"],
    deps = [
        "@hdrhistogram//:libhdrhistogram",
    ],
)
