cc_library(
    name = "utils",
    srcs = [
    ],
    hdrs = [
        "functional.h",
        "hdr_hist.h",
        "mutex.h",
        "named_type.h",
        "static_deleter_fn.h",
    ],
    copts = [
    ],
    include_prefix = "utils",
    visibility = ["//visibility:public"],
    deps = [
        "@hdrhistogram_c",
    ],
)
