cc_library(
    name = "syschecks",
    srcs = [
        "syschecks.cc",
        "pidfile.cc",
    ],
    hdrs = [
        "include/syschecks/syschecks.h",
    ],
    includes = [
        "include",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/v/base",
        "//src/v/ssx",
        "//src/v:version",
    ],
)
