cc_library(
    name = "version",
    hdrs = [
        "version.h",
    ],
    include_prefix = "cluster",
    visibility = ["//visibility:public"],
    deps = [
        "//src/v/utils",
        "//src/v/model",
    ],
)

cc_library(
    name = "features",
    hdrs = [
        "features.h",
    ],
    include_prefix = "cluster",
    visibility = ["//visibility:public"],
    deps = [
        "//src/v/utils",
        "//src/v/model",
    ],
)
