cc_library(
    name = "fundamental",
    hdrs = [
        "fundamental.h",
    ],
    include_prefix = "raft",
    visibility = ["//visibility:public"],
    deps = [
        "//src/v/utils",
    ],
)
