cc_library(
    name = "serde",
    hdrs = glob([
        "*.h",
        "rw/*.h",
    ]),
    copts = [
    ],
    include_prefix = "serde",
    visibility = ["//visibility:public"],
    deps = [
        "//src/v/bytes",
        "//src/v/hashing",
        "//src/v/reflection",
        "//src/v/ssx",
        "//src/v/utils",
    ],
)
