cc_library(
    name = "base",
    hdrs = [
        "include/base/likely.h",
        "include/base/oncore.h",
        "include/base/outcome.h",
        "include/base/seastarx.h",
        "include/base/source_location.h",
        "include/base/units.h",
        "include/base/vassert.h",
        "include/base/vlog.h",
    ],
    includes = [
        "include",
    ],
    visibility = ["//visibility:public"],
)
