cc_library(
    name = "protocol",
    srcs = [
    ],
    hdrs = [
        "types.h",
        "wire.h",
        "batch_reader.h",
        "kafka_batch_adapter.h",
    ],
    include_prefix = "kafka/protocol",
    visibility = ["//visibility:public"],
)
