cc_library(
    name = "types",
    hdrs = [
        "types.h",
        "group_probe.h",
        "latency_probe.h",
        "sasl_probe.h",
    ],
    include_prefix = "kafka",
    visibility = ["//visibility:public"],
    deps = [
    ],
)
