cc_library(
    name = "types",
    hdrs = [
        "group_probe.h",
        "latency_probe.h",
        "sasl_probe.h",
        "types.h",
    ],
    include_prefix = "kafka",
    visibility = ["//visibility:public"],
    deps = [
        "//src/v/kafka/protocol:types",
    ],
)
