cc_library(
    name = "json",
    srcs = [
    ],
    hdrs = [
        "_include_first.h",
        "allocator.h",
        "logger.h",
        "encodings.h",
        "writer.h",
        "stringbuffer.h",
        "json.h",
        "prettywriter.h",
        "reader.h",
        "stream.h",
    ],
    include_prefix = "json",
    visibility = ["//visibility:public"],
    deps = [
    ],
)
