cc_library(
    name = "json",
    srcs = [
    ],
    hdrs = [
        "_include_first.h",
        "allocator.h",
        "document.h",
        "encodings.h",
        "istreamwrapper.h",
        "json.h",
        "logger.h",
        "ostreamwrapper.h",
        "prettywriter.h",
        "reader.h",
        "schema.h",
        "stream.h",
        "stringbuffer.h",
        "writer.h",
        "validator.h",
    ],
    include_prefix = "json",
    visibility = ["//visibility:public"],
    deps = [
        "@rapidjson//:librapidjson",
    ],
)
