name: Lint cpp

on:
  push:
    branches:
      - 'dev'
    paths:
      - '**.h'
      - '**.cc'
      - '**.cpp'
      - '**.proto'
      - '**.java'
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - '**.h'
      - '**.cc'
      - '**.cpp'
      - '**.proto'
      - '**.java'

jobs:
  cpp:
    name: Lint files with clang-format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Baselisk
      run: |
        apt install -y wget
        wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
        chmod +x /usr/local/bin/bazel
    - name: Run clang-format
      run: |
        bazel run //tools:clang_format
        git diff --exit-code
